
name: Modified Docker tests
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - name: Setup Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install inotify
    - name: Run inotifywait
      run: |-
        python3 -c "
        import inotify.adapters
        import inotify.constants
        import os
        from datetime import datetime, timezone
        with open('/home/runner/inotifywait-log-build.csv', 'w') as log_file:
          i = inotify.adapters.InotifyTree('/home/runner/work/openapi-generator/openapi-generator', inotify.constants.IN_CREATE | inotify.constants.IN_ACCESS)
          for event in i.event_gen(yield_nones=False):
            (_, type_names, path, filename) = event
            now = datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%S.%f') + 'Z'
            events = ','.join(type_names)
            log_file.write(f'{now};{path};{filename};{events}\n')
            log_file.flush()
            os.fsync(log_file.fileno())
        " &
    - name: Check out code
      uses: actions/checkout@v4
    - run: touch optcd-3.txt
    - name: Test run-in-docker.sh
      shell: bash
      run: |-
        sed -i 's/ -it / /g' run-in-docker.sh
        ./run-in-docker.sh mvn -B clean install
    - run: touch optcd-4.txt
    - name: Build Dockerfile
      shell: bash
      run: docker build .
    - run: touch optcd-5.txt
    - name: Build modules/openapi-generator-online
      shell: bash
      run: |-
        docker build modules/openapi-generator-online/ -t test
    - run: touch optcd-6.txt
    - name: Build and test modules/openapi-generator-cli
      shell: bash
      run: |-
        cp docker-entrypoint.sh ./modules/openapi-generator-cli
        docker build modules/openapi-generator-cli/ -t cli-test
        docker run --rm -v "${PWD}:/local" cli-test generate \
        -i https://raw.githubusercontent.com/openapitools/openapi-generator/master/modules/openapi-generator/src/test/resources/3_0/petstore.yaml \
        -g go \
        -o /local/out/go
    - run: touch optcd-7.txt
    - name: Upload inotifywait logs
      uses: actions/upload-artifact@v4
      with:
        name: inotifywait-build
        path: /home/runner/inotifywait-log-build.csv
'on':
- push
- workflow_dispatch
